Repository AdaptiveMotorControlLab/CEBRA, pull requests merged in 2023-07, with the labels that each got.

#35 Automatically download the rat-hippocampus dataset
  cebra/data/assets.py
  cebra/data/base.py
  cebra/datasets/hippocampus.py
  tests/test_datasets.py
Labels: CLA signed

#30 Fix dtypes handled in the labels of the decoders
  cebra/integrations/sklearn/decoder.py
  tests/test_sklearn_decoder.py
Labels: bug, CLA signed

#40 Temporarily disable test runs on dev repo
  .github/workflows/build.yml
Labels: CLA signed

#41 Add `...` pattern to copybutton config
  docs/source/conf.py
Labels: bug, documentation, CLA signed

#25 Expose `n_bins` argument from `align_embeddings`
  cebra/integrations/sklearn/metrics.py
  docs/source/api.rst
  docs/source/api/sklearn/helpers.rst
Labels: enhancement, CLA signed

#44 Fix Device in Multisession Training
  cebra/data/datasets.py
  tests/test_sklearn.py
Labels: CLA signed

#43 Support More Data Types in the sklearn Dataset and Decoder
  cebra/data/helper.py
  cebra/distributions/discrete.py
  cebra/helper.py
  cebra/integrations/sklearn/dataset.py
  cebra/integrations/sklearn/decoder.py
  tests/test_integration_train.py
  tests/test_sklearn.py
  tests/test_sklearn_decoder.py
Labels: CLA signed

#34 Improve device support and add support for Apple Silicon chipset (`mps`)
  cebra/helper.py
  cebra/integrations/sklearn/cebra.py
  cebra/integrations/sklearn/utils.py
  cebra/io.py
  tests/test_sklearn.py
Labels: enhancement, CLA signed

#50 Add NLB tools pypi package back as dataset dependency
  setup.cfg
Labels: enhancement, CLA signed

#53 Add Matplotlib ImportError when using compare_models()
  cebra/helper.py
  cebra/integrations/matplotlib.py
  tests/test_plot.py
Labels: CLA signed
