Repository AdaptiveMotorControlLab/CEBRA, pull requests merged in 2023-09, with the labels that each got.

#62 Fix test failures due to http rate limit
  cebra/helper.py
  tests/test_dlc.py
Labels: CLA signed

#59 Autodownload monkey reaching data
  cebra/datasets/monkey_reaching.py
  tests/test_datasets.py
Labels: CLA signed

#64 add demo link to homepage
  README.md
Labels: CLA signed

#55 Fix type bug in to() method
  cebra/integrations/sklearn/cebra.py
  tests/test_sklearn.py
Labels: bug, CLA signed

#66 Release 0.3.0rc1
  Makefile
  PKGBUILD
  cebra/__init__.py
  reinstall.sh
Labels: CLA signed, release

#68 Autodownload synthetic data
  cebra/datasets/__init__.py
  cebra/datasets/synthetic_data.py
Labels: CLA signed

#71 Add thumbnail for openscope notebook
  docs/source/conf.py
Labels: CLA signed
