Repository AdaptiveMotorControlLab/CEBRA, pull requests merged in 2023-05, with the labels that each got.

#9 Release 0.2.0rc3 to PyPI
  .github/workflows/docs.yml
Labels: CLA signed, release

#10 Update website
  docs/root/index.html
Labels: CLA signed

#11 Update README, index.html and license docs
  CLA.md
  LICENSE.md
  README.md
  docs/source/index.rst
Labels: documentation, CLA signed

#12 Raise error on old pytorch version
  cebra/models/model.py
  tests/test_models.py
Labels: CLA signed

#14 Release 0.2.0rc4
  .github/workflows/build.yml
  CITATION.cff
  Makefile
  PKGBUILD
  cebra/__init__.py
  docs/root/index.html
  docs/source/conf.py
  docs/source/installation.rst
  reinstall.sh
  setup.cfg
Labels: CLA signed, release

#15 Release 0.2.0
  .github/workflows/build.yml
  Makefile
  PKGBUILD
  cebra/__init__.py
  reinstall.sh
  setup.cfg
  tests/test_demo.py
  tools/check_for_binary_files.sh
Labels: CLA signed, release

#21 Update usage.rst
  docs/source/usage.rst
Labels: CLA signed
