Repository AdaptiveMotorControlLab/CEBRA, pull requests merged in 2023-12, with the labels that each got.

#113 Update icon link for dandi demo data
  docs/source/conf.py
Labels: CLA signed

#112 Update cebra_paper_m1.yml and cebra.yml
  .github/workflows/build.yml
  conda/cebra.yml
  conda/cebra_paper_m1.yml
Labels: CLA signed

#110 Release 0.3.1
  Dockerfile
  Makefile
  PKGBUILD
  cebra/__init__.py
  reinstall.sh
Labels: CLA signed, release

#114 Add missing error raising and test for `adapt` on Multissession
  cebra/integrations/sklearn/cebra.py
  tests/test_sklearn.py
Labels: bug, CLA signed
