Repository AdaptiveMotorControlLab/CEBRA, pull requests merged in 2023-06, with the labels that each got.

#28 Remove `subsample` default in `OrthogonalProcrustesAlignment`, improve tests
  cebra/data/helper.py
  tests/test_data_helper.py
Labels: CLA signed

#31 Fix action workflow definitions for external contributors
  .github/workflows/doc-coverage.yml
  .github/workflows/docs.yml
Labels: CLA signed

#37 For docs build, limit scikit-learn version
  setup.cfg
Labels: bug, documentation, CLA signed

#38 Temporarily disable PR comment to report doc coverage
  .github/workflows/doc-coverage.yml
Labels: bug, CLA signed

#36 Update repo link on landing page
  docs/root/index.html
Labels: CLA signed

#20 Fix typo in pi_vae.py
  third_party/pivae/pivae_code/pi_vae.py
Labels: documentation, CLA signed
