Repository AdaptiveMotorControlLab/CEBRA, pull requests merged in 2023-10, with the labels that each got.

#69 Improve saving and loading of models
  cebra/integrations/sklearn/cebra.py
  tests/test_sklearn.py
Labels: CLA signed

#80 Update installation.rst
  docs/source/installation.rst
Labels: CLA signed

#70 Improve documentation for local docs build
  .gitignore
  cebra/datasets/hippocampus.py
  cebra/models/multiobjective.py
  docs/source/contributing.rst
  tools/build_docs.sh
Labels: CLA signed

#76 Extend Delta distribution to multiple dimensions
  cebra/data/single_session.py
  cebra/distributions/__init__.py
  cebra/distributions/continuous.py
  tests/test_distributions.py
Labels: CLA signed

#84 Plotly integration
  cebra/integrations/plotly.py
Labels: CLA signed

#86 Fix broadcasting in InfoNCE loss
  cebra/models/criterions.py
  tests/test_criterions.py
Labels: CLA signed

#85 Enhance `ModuleNotFoundError` messages
  cebra/data/load.py
  cebra/datasets/monkey_reaching.py
  tests/test_criterions.py
  tests/test_load.py
Labels: documentation, CLA signed

#87 Fix consistency labels ordering and simplify
  cebra/integrations/matplotlib.py
  cebra/integrations/sklearn/metrics.py
  docs/source/usage.rst
  tests/test_plot.py
  tests/test_sklearn_metrics.py
Labels: CLA signed

#82 Add interactive plots using plotly
  .github/workflows/build.yml
  PKGBUILD
  cebra/integrations/matplotlib.py
  cebra/integrations/plotly.py
  setup.cfg
  tests/test_plotly.py
Labels: enhancement, CLA signed

#67 Release v0.3.0rc2
  .dockerignore
  .github/workflows/doc-coverage.yml
  Dockerfile
  Makefile
  PKGBUILD
  cebra/__init__.py
  cebra/data/assets.py
  cebra/datasets/synthetic_data.py
  cebra/integrations/sklearn/cebra.py
  docs/source/api/sklearn/helpers.rst
  docs/source/contributing.rst
  docs/source/installation.rst
  reinstall.sh
  tests/test_datasets.py
  tests/test_distributions.py
  tests/test_sklearn.py
  tools/build_docker.sh
  tools/build_docs.sh
Labels: CLA signed, release

#91 Pin `tables` <= 3.8
  setup.cfg
Labels: CLA signed

#92 Release v0.3.0
  Dockerfile
  Makefile
  PKGBUILD
  cebra/__init__.py
  reinstall.sh
  tests/test_plotly.py
Labels: CLA signed, release

#96 Auto-import plotly integration
  cebra/__init__.py
  cebra/integrations/__init__.py
Labels: documentation, CLA signed

#98 Update usage.rst
  docs/source/usage.rst
Labels: documentation, CLA signed

#102 Simplify plotly docstring example
  cebra/integrations/plotly.py
Labels: CLA signed

#103 Restructure API docs for integrations
  .github/workflows/docs.yml
  cebra/data/load.py
  cebra/integrations/plotly.py
  docs/source/api.rst
  docs/source/api/integrations/data.rst
  docs/source/api/integrations/deeplabcut.rst
  docs/source/api/integrations/matplotlib.rst
  docs/source/api/integrations/plotly.rst
  docs/source/api/pytorch/helpers.rst
  docs/source/api/pytorch/integrations.rst
  docs/source/conf.py
Labels: CLA signed

#104 Release v0.3.1rc1
  Dockerfile
  Makefile
  PKGBUILD
  README.md
  cebra/__init__.py
  reinstall.sh
  tools/bump_version.sh
Labels: CLA signed, release
