Repository AdaptiveMotorControlLab/CEBRA, pull requests merged in 2024-10, with the labels that each got.

#176 Change pytorch version in docs to stable
  docs/source/conf.py
Labels: CLA signed, 🐞 fix

#184 Fix tests for upgraded dependencies
  cebra/datasets/monkey_reaching.py
  cebra/integrations/plotly.py
  setup.cfg
Labels: CLA signed

#167 Add ruff for linting the codebase
  .pre-commit-config.yaml
  pyproject.toml
Labels: enhancement, good first issue, CLA signed

#166 Extend type checking to all float datatypes
  cebra/data/datasets.py
  cebra/helper.py
Labels: enhancement, CLA signed

#185 Fix linting issues
  cebra/__init__.py
  cebra/__main__.py
  cebra/config.py
  cebra/data/base.py
  cebra/data/datasets.py
  cebra/data/datatypes.py
  cebra/data/helper.py
  cebra/data/load.py
  cebra/data/multi_session.py
  cebra/data/single_session.py
  cebra/datasets/__init__.py
  cebra/datasets/allen/ca_movie.py
  cebra/datasets/allen/ca_movie_decoding.py
  cebra/datasets/allen/combined.py
  cebra/datasets/allen/make_neuropixel.py
  cebra/datasets/allen/neuropixel_movie.py
  cebra/datasets/allen/neuropixel_movie_decoding.py
  cebra/datasets/allen/single_session_ca.py
  cebra/datasets/gaussian_mixture.py
  cebra/datasets/generate_synthetic_data.py
  cebra/datasets/hippocampus.py
  cebra/datasets/make_neuropixel.py
  cebra/datasets/monkey_reaching.py
  cebra/datasets/save_dataset.py
  cebra/distributions/base.py
  cebra/distributions/continuous.py
  cebra/distributions/index.py
  cebra/distributions/mixed.py
  cebra/grid_search.py
  cebra/helper.py
  cebra/integrations/deeplabcut.py
  cebra/integrations/matplotlib.py
  cebra/integrations/plotly.py
  cebra/integrations/sklearn/cebra.py
  cebra/integrations/sklearn/helpers.py
  cebra/integrations/sklearn/metrics.py
  cebra/models/criterions.py
  cebra/models/model.py
  cebra/models/multiobjective.py
  cebra/models/projector.py
  cebra/registry.py
  cebra/solver/base.py
  cebra/solver/multi_session.py
  cebra/solver/single_session.py
  cebra/solver/supervised.py
Labels: enhancement, CLA signed

#180 Set default offset to an Offset object
  cebra/data/datasets.py
Labels: CLA signed, 🐞 fix

#187 Add additional tests for TensorDataset
  cebra/data/datasets.py
  tests/test_datasets.py
Labels: CLA signed

#188 Fix linting errors in tests
  tests/test_api.py
  tests/test_cli.py
  tests/test_criterions.py
  tests/test_datasets.py
  tests/test_demo.py
  tests/test_distributions.py
  tests/test_grid_search.py
  tests/test_integration_train.py
  tests/test_load.py
  tests/test_models.py
  tests/test_plot.py
  tests/test_registry.py
  tests/test_sklearn.py
  tests/test_solver.py
  tests/test_usecases.py
Labels: enhancement, CLA signed
