Repository AdaptiveMotorControlLab/CEBRA, pull requests merged in 2025-04, with the labels that each got.

#241 Upgrade docs build
  .dockerignore
  .github/workflows/build.yml
  .github/workflows/docs.yml
  .gitignore
  cebra/models/criterions.py
  docs/Dockerfile
  docs/Makefile
  docs/README.md
  docs/requirements.txt
  docs/source/conf.py
  docs/source/demos.rst
  setup.cfg
  tools/build_docs.sh
Labels: CLA signed

#242 Allow indexing of the cebra docs
  .github/workflows/docs.yml
  docs/root/robots.txt
Labels: documentation, CLA signed

#246 Fix broken docs coverage workflows
  .github/workflows/build.yml
  .github/workflows/doc-coverage.yml
  setup.cfg
Labels: CLA signed

#237 Update conf.py
  docs/source/conf.py
Labels: CLA signed, xCEBRA🦓

#248 Update docs.yml to build from main
  .github/workflows/docs.yml
Labels: CLA signed

#247 Update installation.rst --> add link to docker hub
  docs/source/installation.rst
Labels: CLA signed
