Repository AdaptiveMotorControlLab/CEBRA, pull requests merged in 2025-01, with the labels that each got.

#200 Concatenate last batches for batched inference
  cebra/solver/base.py
  tests/test_sklearn.py
Labels: CLA signed, 🐞 fix

#212 Update workflows to actions/setup-python@v5, actions/cache@v4
  .github/workflows/build.yml
  .github/workflows/doc-coverage.yml
  .github/workflows/docs.yml
  .github/workflows/release-pypi.yml
Labels: CLA signed

#206 Fix deprecation warning force_all_finite -> ensure_all_finite for sklearn>=1.6
  cebra/integrations/sklearn/utils.py
Labels: CLA signed

#214 Add tests to check legacy model loading
  tests/_build_legacy_model/.gitignore
  tests/_build_legacy_model/Dockerfile
  tests/_build_legacy_model/README.md
  tests/_build_legacy_model/create_model.py
  tests/_build_legacy_model/generate.sh
  tests/test_sklearn_legacy.py
Labels: enhancement, CLA signed
