Repository AdaptiveMotorControlLab/CEBRA, pull requests merged in 2025-02, with the labels that each got.

#190 Add improved goodness of fit implementation
  cebra/integrations/sklearn/metrics.py
  tests/test_sklearn_metrics.py
Labels: enhancement, CLA signed

#221 Support numpy 2, upgrade tests to support torch 2.6
  .github/workflows/build.yml
  cebra/data/load.py
  cebra/integrations/sklearn/cebra.py
  setup.cfg
  tests/test_dlc.py
  tests/test_load.py
Labels: CLA signed

#189 Release 0.5.0rc1
  Dockerfile
  Makefile
  PKGBUILD
  cebra/__init__.py
  cebra/integrations/sklearn/cebra.py
  docs/source/conf.py
  reinstall.sh
  tools/bump_version.sh
Labels: CLA signed, release

#222 Fix pypi action
  .github/workflows/release-pypi.yml
  Dockerfile
  PKGBUILD
  docs/source/contributing.rst
  pyproject.toml
  reinstall.sh
  setup.cfg
  tools/build_docs.sh
  tools/bump_version.sh
Labels: CLA signed, release

#224 Update base.py
  cebra/solver/base.py
Labels: bug, CLA signed
