Repository AdaptiveMotorControlLab/CEBRA, pull requests merged in 2025-03, with the labels that each got.

#227 Change max consistency value to 100 instead of 99
  cebra/integrations/matplotlib.py
Labels: CLA signed, 🐞 fix

#230 Update assets.py --> force check for parent dir
  cebra/data/assets.py
Labels: CLA signed

#229 User docs minor edit
  docs/source/usage.rst
Labels: CLA signed

#232 General Doc refresher
  docs/source/figures.rst
  docs/source/index.rst
  docs/source/installation.rst
  docs/source/usage.rst
Labels: documentation, CLA signed

#231 render plotly in our docs, show code/doc version
  .github/workflows/docs.yml
  cebra/integrations/plotly.py
  docs/Makefile
  docs/source/_static/css/custom.js
  docs/source/conf.py
Labels: documentation, CLA signed

#234 Update conf.py
  docs/source/conf.py
Labels: CLA signed

#228 Refactoring setup.cfg
  AUTHORS.md
  setup.cfg
Labels: CLA signed

#235 Home page landing update
  docs/root/index.html
Labels: documentation, CLA signed, website
